spring:
  application:
    name: notification-service

  config:
    import: optional:file:.env[.properties]

  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    retry:
      backoff: 2000

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

app:
  mail:
    sender:
      name: Sigma-shop
      mail: grzegorzsz884@gmail.com

  rabbitmq:
    queues:
      mail: mail.mailing
      mail-dead-letter: mail.dlq
    exchanges:
      mail: mail.exchange
      mail-dlx-exchange: ${app.rabbitmq.queues.mail}.dlx
    routing-keys:
      mail: mailing-routing-key

s3:
  bucket:
    name: ${BUCKET_NAME}
  region:
    name: ${AWS_REGION:eu-west-3}
  accessKey: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_ACCESS_KEY}

server:
  port: 8083
