spring:
  application:
    name: notification-service

  config:
    import: optional:file:.env[.properties]

  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    retry:
      backoff: 2000

app:
  mail:
    sender:
      name:
      mail:

s3:
  bucket:
    name: ${BUCKET_NAME}
  region:
    name: ${AWS_REGION:eu-west-3}
  accessKey: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_ACCESS_KEY}
