services:
  postgres:
    image: postgres:17.0
    container_name: postgres-product-service
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: product-service
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
