services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_DB_USERNAME: root
      MONGO_DB_PASSWORD: password
      MONGO_DB_DATABASE: cart-service
    volumes:
      - ./data:/data/db