services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_DB_USERNAME: root
      MONGO_DB_PASSWORD: password
      MONGO_DB_DATABASE: cart-service
    volumes:
      - ./data:/data

  redis:
    image: docker.io/library/redis:7.4.0
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass password
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  data: { }
  redis_data: