services:
  mysql:
    image: mysql:8.3.0
    container_name: order-service-mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: order_service
      MYSQL_PASSWORD: mysql
      MYSQL_USER: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3.13.7-management
    container_name: conference-management-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  rabbitmq-data:
