spring:
  application:
    name: order-service
  datasource:
    username: root
    password: mysql
    url: jdbc:mysql://localhost:3306/order_service?autoReconnect=true&createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  config:
    import: optional:file:.env[.properties]

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs

server:
  port: 8081

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: ["*"]
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      inventory:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState:
          seconds: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimum-number-of-calls: 5
  timelimiter:
    instances:
      inventory:
        timeout-duration:
          seconds: 3
  retry:
    instances:
      inventory:
        max-attempts: 3
        wait-duration:
          seconds: 5

app:
  base-url: http://localhost:8081

payment:
  stripe:
    api-key: ${STRIPE_API_KEY}
    webhook-secret-key: ${STRIPE_WEBHOOK_SECRET_KEY}
  check-status-delay: PT3M
  payment-max-age: 15