spring:
  application:
    name: cart-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/cart-service
    redis:
      host: localhost
      port: 6379
      password: password

  cache:
    type: redis