services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql-inventory
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: inventory-service
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
